### PR TITLE
Doc/ge example

### PR DESCRIPTION
**Pull request by prashantmital**
LU-Decomposition performed using custom uFunc.

### CODE REVIEW

**Comment by prashantmital** [comment]
@markkness here it is!

**Comment by prashantmital** [comment]
@bgrant: Just cleaned up the example notebook. Still haven't managed to get the cyclic case working, this will make for a much more compelling example if I can do that. Regardless, we can look to merge changes in the current state even as I spend tomorrow making a final push to get cyclic functional.

**Comment by markkness** [comment]
I do really like this example. 
But I think that something may be missing: I expected that there would either be
1) Two matrices, L and U, lower and upper triangular, that factor the original matrix, or
2) The row calculations are also applied to the right-hand side, so that the resulting upper triangular matrix can be used to solve the linear system.
As-is, with this just generating one upper triangular matrix, it is not clear to me how it would apply to a real problem, e.g. like Ax = b, with A the n-by-n matrix, b the n-by-1 rhs, and x the n-by-1 unknowns.

As a related issue, if you did have a right-hand side somewhere, you could show that the original matrix times the calculated unknowns did in fact equal the original right-hand-side, thus showing that you really did calculate what you said you did.

**Comment by bgrant** [comment]
Hey @prashantmital : can you remove the quickstart from this PR, since you have it in the other?

**Comment by bgrant** [comment]
Small recommendations on your last cell:

Rather than initializing your dict by hand:

```python
performance_data = dict()
for scheme in distributions:
    performance_data[scheme] = list()
```

you could use a `defaultdict`:

```python
from collections import defaultdict

performance_data = defaultdict(list)
```


Also, You could eliminate the unused name `p1` on that last line.

```python
p1,=plt.plot(sizes, performance_data[scheme], label=str(scheme), linewidth=2)
```

**Comment by bgrant** [comment]
In `parallel_gauss_elim`:

You should be able to get the global shape from the local `distribution`, rather than having to pass it into the function:

https://github.com/enthought/distarray/blob/master/distarray/localapi/maps.py#L97

**Comment by prashantmital** [comment]
removed `quickstart` from PR

**Comment by bgrant** [comment]
in `parallel_gauss_elim`:

If you're doing what I think here (trimming your slices to match the bounds of the local array)

```python
    # limit the slices using actual size of local array
    n_rows_local, n_cols_local = darray.ndarray.shape
    i_indices, j_indices = (i_slice.indices(n_rows_local), 
                            j_slice.indices(n_cols_local))
```

you may not need to, as slices do this for you already.

Example:

```python
In [143]: arr = np.random.random((3, 4))

In [144]: arr
Out[144]:
array([[ 0.85050331,  0.10514387,  0.59279957,  0.86352332],
       [ 0.31740292,  0.01144302,  0.98903874,  0.80529378],
       [ 0.54420277,  0.87015639,  0.87865956,  0.53952124]])

In [145]: arr[0, -100000:1000000]
Out[145]: array([ 0.85050331,  0.10514387,  0.59279957,  0.86352332])
```

**Comment by bgrant** [comment]
Thanks for taking a look @markkness!  He's working on some of your
suggestions.

**Comment by prashantmital** [comment]
@markkness : just added a section that explains and performs LU decomposition. I felt this was more illustrative than the simple back substitution to solve Ax=b!

**Comment by markkness** [comment]
Very nice, I like the discussion of the LU factorization.
This is really a good example, this is obviously very practically relevant.
I did see an error in the IPython notebook, around In[9], the last bit before the LU discussion.
Other than that, LGTM.

**Comment by prashantmital** [comment]
Corrected the plotting error. Safe to merge.

**Comment by bgrant** [comment]
Looks great @prashantmital - thanks.

**Pull request merged**
